// The 8 core behavioral dimensions used for assessment
export type BehavioralDimension = 'spend' | 'loyalty' | 'investment' | 'interest' | 'greenisity' | 'social' | 'novelty' | 'value';

// Represents the application's current view state
export type AppStage =
  | 'INPUT'
  | 'BENTO_APPROVAL'
  | 'ASSESSMENT'
  | 'PERSONA_RESULT'
  | 'CHAT';

// The structured business context generated by the AI
export interface BentoPanel {
  colSpan: number;
  rowSpan: number;
  data: PanelContent;
}

export interface Bento {
  id: string;
  type: string; // e.g., 'business-model', 'swot'
  businessDescription: string;
  panels: BentoPanel[];
  timestamp: number;
}

// A single assessment statement tied to a dimension
export interface Statement {
  dimension: string;
  text: string;
  id?: string;
  imageUrl?: string;
}

// The final, actionable persona generated by the AI
export interface Persona {
  id: string;
  name: string;
  age: number;
  role: string;
  experience: string;
  bio: string;
  interests: string;
  disinterests: string;
  imageUrl?: string;
}

// Type for the assessment results sent to the persona generation API
export interface AssessmentResult {
  dimension: string;
  score: number;
  text?: string;
}

export interface ChatMessage {
  role: 'user' | 'persona';
  content: string;
}

export type Document = {
  name:string;
  size: number;
  lastModified: string;
}

// --- BENTO BOX RICH PANEL TYPES ---

// Each panel's data will be a discriminated union based on its type.
export type PanelContent =
  | { type: 'text'; title: string; content: string }
  | { type: 'feature-large-text'; label: string; value: string }
  | { type: 'competitors'; title: string; competitors: { name: string; domain: string }[] };
  // Future types to be added here:
  // | { type: 'hero-image'; imageUrl: string }
  // | { type: 'icon-feature'; iconName: string; title: string } 