// The 8 core behavioral dimensions used for assessment
export type BehavioralDimension = 'spend' | 'loyalty' | 'investment' | 'interest' | 'greenisity' | 'social' | 'novelty' | 'value';

// Represents the application's current view state
export type AppStage =
  | 'INPUT'
  | 'BENTO_APPROVAL'
  | 'ASSESSMENT'
  | 'PERSONA_RESULT'
  | 'CHAT';

// The structured business context generated by the AI
export interface Bento {
  id: string;
  businessDescription: string;
  businessModel: string;
  customerChallenge: string;
  productService: string;
  positioning: string;
  whyWeExist: string;
  competitors: { name: string; domain: string }[];
  timestamp: number;
}

// A single assessment statement tied to a dimension
export interface Statement {
  dimension: string;
  text: string;
  id?: string;
  imageUrl?: string;
}

// The final, actionable persona generated by the AI
export interface Persona {
  name: string;
  age: number;
  role: string;          // e.g., "Lead Teacher", "Marketing Manager"
  experience: string;    // e.g., "6 years", "10 years as a manager"
  bio: string;           // A 2-3 sentence summary
  interests: string;     // A few key interests
  disinterests: string;  // A few key disinterests
  insights: string;      // Actionable insights for the business owner (for the bot's brain)
  imageUrl: string | null;
}

// Type for the assessment results sent to the persona generation API
export interface AssessmentResult {
  dimension: string;
  score: number;
  text?: string;
}

export interface ChatMessage {
  role: 'user' | 'persona';
  content: string;
}

export type Document = {
  name:string;
  size: number;
  lastModified: string;
} 