// The 8 core behavioral dimensions used for assessment
export type BehavioralDimension = 'spend' | 'loyalty' | 'investment' | 'interest' | 'greenisity' | 'social' | 'novelty' | 'value';

// Represents the application's current view state
export type AppStage = 'INPUT' | 'BENTO_APPROVAL' | 'ASSESSMENT' | 'PERSONA_RESULT';

// The structured business context generated by the AI
export interface Bento {
  businessModel: string;
  customerChallenge: string;
}

// A single assessment statement tied to a dimension
export interface Statement {
  text: string;
  dimension: BehavioralDimension;
}

// The final, actionable persona generated by the AI
export interface Persona {
  title: string;
  personaName: string;
  visualDescriptor: string; // A detailed prompt for an image generator
  summary: string;
  actionableInsights: {
    title: string;
    insight: string;
  }[];
}

// Type for the assessment results sent to the persona generation API
export type AssessmentResult = {
  dimension: BehavioralDimension;
  score: number; // -1 for disagree, 0 for neutral, 1 for agree
}; 